# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c7f7a766c759195d5ea9e934c7347520bf01a3ffeed6e75ed33205b3026e0ed080982be82a557297eaf14222c14321a38c62d4a7e09534102e8810cc85526f5

test:
  secret_key_base: 4b489a3b1f3a4fa462650e45d0c84b1e95cbbb52adcfc194d4678982be9320e5b7338beed100c3969fe8f40ce36f86b514e0eac63134d2adb873322f8a2ab0b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
